control_master_host: sdr-infra
work_dir: tmp/repos
light_mode: false
num_parallel_processes: 4
progress_file:
  enabled: false # enable to log one file per repo in the location specified below
  location: 'tmp'
supported_envs:
  qa: https://sul-nagios-stage.stanford.edu/nagios/cgi-bin/status.cgi?hostgroup=infrastructure-qa&style=detail&servicestatustypes=28&hoststatustypes=15
  prod: https://sul-nagios-prod.stanford.edu/nagios/cgi-bin/status.cgi?hostgroup=infrastructure-prod&style=detail&servicestatustypes=28&hoststatustypes=15
  stage: https://sul-nagios-stage.stanford.edu/nagios/cgi-bin/status.cgi?hostgroup=infrastructure-stage&style=detail&servicestatustypes=28&hoststatustypes=15
repositories:
  - name: sul-dlss/argo
    cocina_models_update: true
  - name: sul-dlss/common-accessioning
    cocina_models_update: true
  - name: sul-dlss/dlme-airflow
    non_standard_envs:
      - dev
    exclude_envs:
      - prod
      - stage
      - qa
  - name: sul-dlss/dor-services-app
    cocina_models_update: true
  - name: sul-dlss/gis-robot-suite
    cocina_models_update: true
  - name: sul-dlss/google-books
    cocina_models_update: true
  - name: sul-dlss/happy-heron
    cocina_models_update: true
  - name: sul-dlss/hungry-hungry-hippo
    cocina_models_update: true
  - name: sul-dlss/hydra_etd
    cocina_models_update: true
    non_standard_envs:
      - uat
  - name: sul-dlss/modsulator-app-rails
  - name: sul-dlss/pre-assembly
    cocina_models_update: true
  - name: sul-dlss/preservation_catalog
  - name: sul-dlss/preservation_robots
  - name: sul-dlss/rialto-orgs
    exclude_envs:
      - qa
  - name: sul-dlss/robot-console
  - name: sul-dlss/sdr-api
    cocina_models_update: true
  - name: sul-dlss/speech-to-text # deployment to AWS is handled by a Github Action
    exclude_envs:
      - prod
      - stage
      - qa
  - name: sul-dlss/sul_pub
    non_standard_envs:
      - uat
  - name: sul-dlss/suri-rails
  - name: sul-dlss/technical-metadata-service
  - name: sul-dlss/was-pywb
  - name: sul-dlss/was-registrar-app
    cocina_models_update: true
  - name: sul-dlss/was_robot_suite
    cocina_models_update: true
  - name: sul-dlss/workflow-server-rails
